import { atom } from "recoil";
import { Review } from "@/types";

export const reviews = atom({
  key: "reviews",
  default: [
    {
      id: 1,
      restaurant: "Il posto felice",
      rating: 3,
      product: 1,
      plates: 0,
      ospitality: 1,
      location: 2,
      longitude: 9.1203598,
      latitude: 45.4459139,
      review: "",
      address: "Via Lorenteggio, 240, 20147 Milano MI",
      approved: false,
    },
    {
      id: 2,
      restaurant: "Macelleria Equina",
      rating: 5,
      product: 5,
      plates: 5,
      ospitality: 3,
      location: 1,
      longitude: 9.1336118,
      latitude: 45.448617,
      review: "",
      address: "Via Lorenteggio, 177, 20147 Milano MI",
      approved: true,
    },
    {
      id: 3,
      restaurant: "Totò",
      rating: 4,
      product: 3,
      plates: 2,
      ospitality: 3,
      location: 1,
      longitude: 9.123238,
      latitude: 45.4551841,
      review: "",
      address: "Via Angelo Inganni, 83, 20147 Milano MI",
      approved: true,
    },
  ] as Review[],
});
